### ISSUE TITLE
Q

### ISSUE THREAD

**Issue by brendancol** [parietal-io/py-rbush#12]
Message:
 > why is each node's `children` represented as a list of stacks of nodes (in https://github.com/parietal-io/py-rbush/blob/master/rbush/_numba.py)? 
> 
> This strikes me as a workaround to a numba limitation, but also looks like low-hanging fruit for optimization. Perhaps you had a good reason for doing that? Not trying to be critical here, just genuinely curious and trying to help.

**Comment by chbrandt** [comment]
Because I wanted to abstract the `Stack` object, from the main code.

If `Stack` is provided straight to the Tree (say, looping through children), calls to `next` and `data` would have to be explicitly called by the main code functions. Which is not only ugly, but would make maintanance harder.

That is the reason why `List` exist: to abstract operations over `Stack`.
